/// Flutter icons Infoicon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Infoicon
///      fonts:
///       - asset: fonts/Infoicon.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Infoicon {
  Infoicon._();

  static const _kFontFam = 'Infoicon';
  static const _kFontPkg = null;

  static const IconData database = const IconData(0xf1c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
